name: Python CI/CD

# Workflow triggers: Runs on push & pull requests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Clones the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install required dependencies

      - name: Run Pytest with Coverage
        run: pytest --cov=app tests/  # Run tests with coverage

      - name: Run Flake8
      run: |
        flake8 app/ --count --max-line-length=88 --show-source --statistics
